def print_1000_times(text: str, times: int) -> None:
    """
    Prints text times times.
    :param text: text to print
    :param times: number of times to print
    :return: None

       generated by https://t.me/CodefyBot 
    """
    for i in range(times):
        print(text)


print_1000_times("Спасибо дорогой Руслан!", 1000)